services:
  app:
    build: .
    container_name: laravel_horizon_tag_search
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 9002:9000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_horizon_tag_search_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horizon
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: laravel_horizon_tag_searh_redis
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
